spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:1
    driverClassName: org.h2.Driver
    username: root
    password: admin123
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect